### ISSUE TITLE
Sponge does not work on version 3.5.0

### ISSUE THREAD

**Issue by GuardedAirplane** [TheLimePixel/Modern-Skyblock-3#805]
**Describe the bug**
Server crashes when SpongeForge is installed. It appears to be caused by "java.lang.NoClassDefFoundError: net/minecraft/world/chunk/BlockStateContainer"

**To Reproduce**
1. Download version 3.5.0 server
2. Install SpongeForge version 1.12.2-2768-7.1.4 or 1.12.2-2768-7.1.5-RC3506 (both don't work)
3. Run server

**Crash Reports**
See attached files.
[fullLog.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2577908/fullLog.txt)
[crash-2018-11-13_15.15.09-server.txt](https://github.com/EmosewaPixel/Modern-Skyblock-3/files/2577911/crash-2018-11-13_15.15.09-server.txt)

**Pack Information**
 - Pack version: 3.5.0
 - Pack Mode: Gated
 - SP or MP: MP
 - Added Mods: SpongeForge

**Screenshots**
N/A

**Additional context**
Running Java build 1.8.0_181-b13
